# Generated by Django 5.2.4 on 2025-12-21 18:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('numero_bi', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número do BI')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('numero_matricula', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Número de Matrícula')),
                ('telefone', models.JSONField(default=list, verbose_name='Telefones')),
                ('provincia_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=100, null=True)),
                ('senha_hash', models.CharField(max_length=255, verbose_name='Senha')),
                ('genero', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, null=True)),
                ('status_aluno', models.CharField(choices=[('Activo', 'Activo'), ('Expulso', 'Expulso'), ('Transferido', 'Transferido'), ('Suspenso', 'Suspenso')], default='Activo', max_length=20, verbose_name='Status')),
                ('modo_user', models.CharField(default='Inativo', max_length=20, verbose_name='Modo Usuário')),
                ('img_path', models.TextField(blank=True, null=True, verbose_name='Foto')),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'aluno',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='AreaFormacao',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_area_formacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_area', models.CharField(max_length=150, verbose_name='Nome da Área')),
            ],
            options={
                'verbose_name': 'Área de Formação',
                'verbose_name_plural': 'Áreas de Formação',
                'db_table': 'area_formacao',
                'ordering': ['nome_area'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cargo', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['nome_cargo'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['nome_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.SmallIntegerField(verbose_name='Nível')),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'db_table': 'classe',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id_inscricao', models.AutoField(primary_key=True, serialize=False)),
                ('data_inscricao', models.DateField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('nome_candidato', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Candidato')),
                ('documento_candidato', models.JSONField(blank=True, null=True, verbose_name='Documento')),
                ('resultado_avaliacao', models.CharField(blank=True, max_length=80, null=True, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'inscricao',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sala', models.SmallIntegerField(verbose_name='Número da Sala')),
                ('capacidade_alunos', models.IntegerField(verbose_name='Capacidade')),
                ('img_path', models.JSONField(default=list, verbose_name='Imagens')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'sala',
                'ordering': ['numero_sala'],
            },
        ),
        migrations.CreateModel(
            name='TipoDisciplina',
            fields=[
                ('id_tipo_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo', models.CharField(max_length=80, verbose_name='Nome do Tipo')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Disciplina',
                'verbose_name_plural': 'Tipos de Disciplina',
                'db_table': 'tipo_disciplina',
            },
        ),
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_encarregado', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('telefone', models.JSONField(default=list, verbose_name='Telefones')),
                ('provincia_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=100, null=True)),
                ('senha_hash', models.CharField(max_length=255, verbose_name='Senha')),
                ('img_path', models.TextField(blank=True, null=True, verbose_name='Foto')),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Encarregado',
                'verbose_name_plural': 'Encarregados',
                'db_table': 'encarregado',
                'ordering': ['nome_completo'],
                'indexes': [models.Index(fields=['email'], name='encarregado_email_0012bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_fatura', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('id_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'db_table': 'fatura',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('numero_bi', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número do BI')),
                ('codigo_identificacao', models.CharField(max_length=50, unique=True, verbose_name='Código de Identificação')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('genero', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('provincia_residencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Província')),
                ('municipio_residencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('bairro_residencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('senha_hash', models.CharField(max_length=255, verbose_name='Senha')),
                ('status_funcionario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Demitido', 'Demitido'), ('Banido', 'Banido')], default='Activo', max_length=20, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('img_path', models.TextField(blank=True, null=True, verbose_name='Foto')),
                ('id_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionario',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('caminho_pdf', models.TextField(blank=True, null=True, verbose_name='Caminho do PDF')),
                ('imagem_carimbo', models.TextField(blank=True, null=True, verbose_name='Carimbo/Assinatura')),
                ('uuid_documento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('id_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.aluno', verbose_name='Aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_criados', to='apis.funcionario', verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Disciplina')),
                ('carga_horaria', models.IntegerField(blank=True, null=True, verbose_name='Carga Horária')),
                ('id_coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas_coordenadas', to='apis.funcionario', verbose_name='Coordenador')),
                ('id_tipo_disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.tipodisciplina', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'disciplina',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_departamento', models.CharField(max_length=150, verbose_name='Nome do Departamento')),
                ('chefe_id_funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_chefiados', to='apis.funcionario', verbose_name='Chefe')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['nome_departamento'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=150, verbose_name='Nome do Curso')),
                ('duracao_meses', models.IntegerField(blank=True, null=True, verbose_name='Duração (meses)')),
                ('id_area_formacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.areaformacao', verbose_name='Área de Formação')),
                ('id_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_coordenados', to='apis.funcionario', verbose_name='Coordenador')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'ordering': ['nome_curso'],
            },
        ),
        migrations.CreateModel(
            name='CargoFuncionario',
            fields=[
                ('id_cargo_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.cargo', verbose_name='Cargo')),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Cargo-Funcionário',
                'verbose_name_plural': 'Cargos-Funcionários',
                'db_table': 'cargo_funcionario',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='areaformacao',
            name='id_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_coordenadas', to='apis.funcionario', verbose_name='Responsável'),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_accao', models.CharField(max_length=50, verbose_name='Tipo de Ação')),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('id_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.aluno', verbose_name='Aluno')),
                ('id_funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
                'db_table': 'historico',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoLogin',
            fields=[
                ('id_historico_login', models.AutoField(primary_key=True, serialize=False)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('dispositivo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dispositivo')),
                ('navegador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Navegador')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Entrada')),
                ('hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('id_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.aluno', verbose_name='Aluno')),
                ('id_encarregado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.encarregado', verbose_name='Encarregado')),
                ('id_funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Histórico de Login',
                'verbose_name_plural': 'Históricos de Login',
                'db_table': 'historico_login',
                'ordering': ['-hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('editora', models.CharField(blank=True, max_length=150, null=True, verbose_name='Editora')),
                ('caminho_arquivo', models.TextField(blank=True, null=True, verbose_name='Arquivo Digital')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.categoria', verbose_name='Categoria')),
                ('id_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros_gerenciados', to='apis.funcionario', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'livro',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=80, null=True, verbose_name='Método de Pagamento')),
                ('comprovante_path', models.TextField(blank=True, null=True, verbose_name='Comprovante')),
                ('id_fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.fatura', verbose_name='Fatura')),
                ('id_recebedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_recebidos', to='apis.funcionario', verbose_name='Recebedor')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pagamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10)),
                ('id_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_responsaveis', to='apis.funcionario', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Seccao',
            fields=[
                ('id_seccao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_seccao', models.CharField(max_length=150, verbose_name='Nome da Seção')),
                ('id_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
                'db_table': 'seccao',
                'ordering': ['nome_seccao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoDocumento',
            fields=[
                ('id_solicitacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('status_solicitacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('pago', 'Pago')], default='pendente', max_length=20, verbose_name='Status')),
                ('caminho_arquivo', models.TextField(blank=True, null=True, verbose_name='Arquivo Gerado')),
                ('uuid_documento', models.UUIDField(blank=True, null=True, verbose_name='UUID do Documento')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('id_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.aluno', verbose_name='Aluno')),
                ('id_encarregado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.encarregado', verbose_name='Encarregado')),
                ('id_funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_gerenciadas', to='apis.funcionario', verbose_name='Funcionário Responsável')),
            ],
            options={
                'verbose_name': 'Solicitação de Documento',
                'verbose_name_plural': 'Solicitações de Documentos',
                'db_table': 'solicitacao_documento',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_turma', models.CharField(max_length=50, unique=True, verbose_name='Código da Turma')),
                ('ano', models.SmallIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('id_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.classe', verbose_name='Classe')),
                ('id_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.curso', verbose_name='Curso')),
                ('id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.periodo', verbose_name='Período')),
                ('id_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_responsaveis', to='apis.funcionario', verbose_name='Responsável')),
                ('id_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turma',
                'ordering': ['codigo_turma'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorDisciplina',
            fields=[
                ('id_professor_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.disciplina', verbose_name='Disciplina')),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.funcionario', verbose_name='Professor')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Professor-Disciplina',
                'verbose_name_plural': 'Professores-Disciplinas',
                'db_table': 'professor_disciplina',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_avaliacao', models.CharField(choices=[('Prova do Professor', 'Prova do Professor'), ('Prova Trimestral', 'Prova Trimestral'), ('Avaliação Continua', 'Avaliação Contínua')], max_length=30, verbose_name='Tipo de Avaliação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Nota')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Lançamento')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.aluno', verbose_name='Aluno')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.disciplina', verbose_name='Disciplina')),
                ('id_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.funcionario', verbose_name='Professor')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('data_matricula', models.DateField(auto_now_add=True, verbose_name='Data de Matrícula')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.aluno', verbose_name='Aluno')),
                ('id_turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matricula',
                'ordering': ['-data_matricula'],
            },
        ),
        migrations.CreateModel(
            name='FaltaAluno',
            fields=[
                ('id_falta', models.AutoField(primary_key=True, serialize=False)),
                ('data_falta', models.DateField(verbose_name='Data da Falta')),
                ('justificada', models.BooleanField(default=False, verbose_name='Justificada')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.aluno', verbose_name='Aluno')),
                ('id_disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.disciplina', verbose_name='Disciplina')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'Faltas',
                'db_table': 'falta_aluno',
                'ordering': ['-data_falta'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.turma', verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='DisciplinaCurso',
            fields=[
                ('id_disciplina_curso', models.AutoField(primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.curso', verbose_name='Curso')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina-Curso',
                'verbose_name_plural': 'Disciplinas-Cursos',
                'db_table': 'disciplina_curso',
                'unique_together': {('id_curso', 'id_disciplina')},
            },
        ),
        migrations.CreateModel(
            name='AlunoEncarregado',
            fields=[
                ('id_aluno_encarregado', models.AutoField(primary_key=True, serialize=False)),
                ('grau_parentesco', models.CharField(blank=True, max_length=80, null=True, verbose_name='Grau de Parentesco')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.aluno', verbose_name='Aluno')),
                ('id_encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.encarregado', verbose_name='Encarregado')),
            ],
            options={
                'verbose_name': 'Aluno-Encarregado',
                'verbose_name_plural': 'Alunos-Encarregados',
                'db_table': 'aluno_encarregado',
                'unique_together': {('id_aluno', 'id_encarregado')},
            },
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['status'], name='fatura_status_938c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['id_aluno'], name='fatura_id_alun_6b1be9_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['email'], name='funcionario_email_5e0273_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['id_cargo'], name='funcionario_id_carg_2b5c12_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['id_aluno'], name='documento_id_alun_c5794a_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['uuid_documento'], name='documento_uuid_do_2f848f_idx'),
        ),
        migrations.AddIndex(
            model_name='historico',
            index=models.Index(fields=['data_hora'], name='historico_data_ho_79493f_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaodocumento',
            index=models.Index(fields=['status_solicitacao'], name='solicitacao_status__4c80d5_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaodocumento',
            index=models.Index(fields=['id_aluno'], name='solicitacao_id_alun_dd4134_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='professordisciplina',
            unique_together={('id_funcionario', 'id_disciplina', 'id_turma')},
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['id_aluno', 'id_disciplina'], name='nota_id_alun_7303c0_idx'),
        ),
        migrations.AddIndex(
            model_name='faltaaluno',
            index=models.Index(fields=['id_aluno', 'data_falta'], name='falta_aluno_id_alun_358daa_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['status_aluno'], name='aluno_status__20aead_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['id_turma'], name='aluno_id_turm_6e7237_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['email'], name='aluno_email_d96a04_idx'),
        ),
    ]
