# Generated by Django 5.2.4 on 2025-12-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='caminho_arquivo',
            field=models.FileField(upload_to='static/library/books/', verbose_name='Arquivo em PDF'),
        ),
    ]
