# Generated by Django 5.2.7 on 2026-01-17 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        # AlterField removed manually to fix consistency issue
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_candidato', models.AutoField(primary_key=True, serialize=False)),
                ('numero_inscricao', models.CharField(editable=False, max_length=20, unique=True)),
                ('nome_completo', models.CharField(max_length=150)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('numero_bi', models.CharField(max_length=20, unique=True)),
                ('nacionalidade', models.CharField(default='Angolana', max_length=50)),
                ('residencia', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('escola_proveniencia', models.CharField(max_length=150)),
                ('municipio_escola', models.CharField(max_length=100)),
                ('ano_conclusao', models.IntegerField()),
                ('media_final', models.DecimalField(decimal_places=2, max_digits=4)),
                ('turno_preferencial', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=20)),
                ('nome_encarregado', models.CharField(max_length=150)),
                ('parentesco_encarregado', models.CharField(max_length=50)),
                ('telefone_encarregado', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Pago', 'Pago'), ('Agendado', 'Agendado'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Matriculado', 'Matriculado')], default='Pendente', max_length=20)),
                ('curso_primeira_opcao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos_opcao1', to='apis.curso')),
                ('curso_segunda_opcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos_opcao2', to='apis.curso')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'candidato',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ExameAdmissao',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_exame', models.AutoField(primary_key=True, serialize=False)),
                ('data_exame', models.DateTimeField()),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exame', to='apis.candidato')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.sala')),
            ],
            options={
                'verbose_name': 'Exame de Admissão',
                'db_table': 'exame_admissao',
            },
        ),
        migrations.CreateModel(
            name='RupeCandidato',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_rupe', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], default='Pendente', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rupes', to='apis.candidato')),
            ],
            options={
                'db_table': 'rupe_candidato',
            },
        ),
    ]
