# Generated by Django 5.2.4 on 2025-12-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_livro_caminho_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='img_path',
            field=models.ImageField(upload_to='m', verbose_name='Imagem da Sala'),
        ),
    ]
