# Generated by Django 5.2.7 on 2026-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_curso_duracao_meses_candidato_exameadmissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='candidatos/certificados/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='comprovativo_bi',
            field=models.FileField(blank=True, null=True, upload_to='candidatos/bi/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto_passe',
            field=models.ImageField(blank=True, null=True, upload_to='candidatos/fotos/'),
        ),
        # AlterField removed manually
    ]
