# Generated by Django 5.2.7 on 2026-01-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_candidato_certificado_candidato_comprovativo_bi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracao_meses',
            field=models.IntegerField(blank=True, db_column='duracao', null=True, verbose_name='Duração (meses)'),
        ),
    ]
