# Generated by Django 5.2.7 on 2026-01-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_sala_img_path'),
        ('apis', '0004_alter_curso_duracao_meses'),
    ]

    operations = [
    ]
