# Generated by Django 5.2.7 on 2026-01-18 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_merge_20260118_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='img_path',
        ),
        migrations.AddField(
            model_name='sala',
            name='bloco',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Bloco'),
        ),
    ]
