# Generated by Django 5.2.7 on 2026-01-18 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_remove_curso_duracao_meses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='duracao_meses',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='imagem_carimbo',
        ),
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.IntegerField(blank=True, default=4, null=True, verbose_name='Duração (Anos)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='image/alunos/', verbose_name='Foto do Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero_bi',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Número do BI'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='senha_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_aluno',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Expulso', 'Expulso'), ('Transferido', 'Transferido'), ('Suspenso', 'Suspenso')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(max_length=10, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='caminho_pdf',
            field=models.FileField(upload_to='documentos/documents/pdfs/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('DECLARAÇÃO', 'DECLARAÇÃO'), ('BOLETIM', 'BOLETIM'), ('CERTIFICADO', 'CERTIFICADO')], max_length=100, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='uuid_documento',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='CÓDIGO ÚNICO DO DOCUMENTO'),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='image/encarregados/images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='image/funcionario/images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dados_anteriores',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Dados Anteriores'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dados_novos',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Dados Novos'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='id_aluno',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='id_funcionario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='tipo_accao',
            field=models.CharField(editable=False, max_length=50, verbose_name='Tipo de Ação'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='dispositivo',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='hora_saida',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Hora de Saída'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='id_aluno',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='id_encarregado',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.encarregado', verbose_name='Encarregado'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='id_funcionario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='ip_usuario',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='navegador',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Navegador'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='caminho_arquivo',
            field=models.FileField(upload_to='documentos/library/books/', verbose_name='Arquivo em PDF'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.CharField(blank=True, default="<attribute 'year' of 'datetime.date' objects>", null=True, verbose_name='Ano'),
        ),
    ]
