# Generated by Django 5.2.7 on 2026-01-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_remove_curso_duracao_meses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLectivo',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_ano', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: 2025/2026', max_length=20, unique=True, verbose_name='Ano Lectivo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo?')),
            ],
            options={
                'verbose_name': 'Ano Lectivo',
                'verbose_name_plural': 'Anos Lectivos',
                'db_table': 'ano_lectivo',
                'ordering': ['-nome'],
            },
        ),
    ]
