# Generated by Django 5.2.7 on 2026-01-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_anolectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
