# Generated by Django 5.2.7 on 2026-01-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='status',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa'), ('Finalizada', 'Finalizada')], default='Ativa', max_length=20, verbose_name='Estado da Turma'),
        ),
    ]
