# Generated by Django 5.2.7 on 2026-01-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_turma_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='status',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Concluida', 'Concluída')], default='Ativa', max_length=20, verbose_name='Estado da Turma'),
        ),
    ]
