# Generated by Django 5.2.7 on 2026-01-20 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_turma_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='id_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.curso', verbose_name='Curso'),
        ),
    ]
