# Generated by Django 5.2.7 on 2026-01-23 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_alter_turma_id_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='ano_lectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.anolectivo', verbose_name='Ano Lectivo'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='ano_lectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.anolectivo', verbose_name='Ano Lectivo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ano_lectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.anolectivo', verbose_name='Ano Lectivo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_lectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.anolectivo', verbose_name='Ano Lectivo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.CharField(blank=True, default="<attribute 'year' of 'datetime.date' objects>", null=True, verbose_name='Ano (Legacy)'),
        ),
    ]
