# Generated by Django 5.2.7 on 2026-01-24 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_candidato_ano_lectivo_fatura_ano_lectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='email_encarregado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='numero_bi_encarregado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoEscolar',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('escola_origem', models.CharField(max_length=200, verbose_name='Escola de Origem')),
                ('ano_lectivo', models.CharField(max_length=20, verbose_name='Ano Lectivo')),
                ('classe', models.CharField(max_length=50, verbose_name='Classe Concluída')),
                ('turma_origem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma Original')),
                ('numero_processo_origem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Processo Anterior')),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Média Final')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/historico_escolar/', verbose_name='Comprovativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_escolar', to='apis.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Histórico Escolar',
                'verbose_name_plural': 'Históricos Escolares',
                'db_table': 'historico_escolar',
                'ordering': ['-ano_lectivo'],
            },
        ),
    ]
