# Generated by Django 5.2.7 on 2026-01-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_candidato_email_encarregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='permissoes_adicionais',
            field=models.JSONField(blank=True, default=list, verbose_name='Permissões Adicionais'),
        ),
    ]
