# Generated by Django 5.2.7 on 2026-01-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_funcionario_permissoes_adicionais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('prioridade', models.IntegerField(default=0, help_text='Maior numero = maior prioridade')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Chamado', 'Chamado'), ('Expirado', 'Expirado')], default='Aguardando', max_length=20)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='apis.candidato')),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
                'db_table': 'lista_espera',
                'ordering': ['-prioridade', 'data_entrada'],
            },
        ),
    ]
