# Generated by Django 5.2.7 on 2026-01-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_listaespera'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='deficiencia',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
    ]
