# Generated by Django 5.2.7 on 2026-01-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_candidato_deficiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='naturalidade',
            field=models.CharField(default='Luanda', max_length=100, verbose_name='Naturalidade (Província)'),
        ),
    ]
