# Generated by Django 5.2.7 on 2026-01-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_candidato_naturalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='tipo_escola',
            field=models.CharField(choices=[('Pública', 'Pública'), ('Privada', 'Privada')], default='Pública', max_length=20),
        ),
    ]
