# Generated by Django 5.2.7 on 2026-01-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_candidato_tipo_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='profissao_encarregado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='residencia_encarregado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='telefone_alternativo_encarregado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
