# Generated by Django 5.2.7 on 2026-01-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_candidato_profissao_encarregado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('candidaturas_abertas', models.BooleanField(default=True, verbose_name='Inscrições Online Abertas')),
                ('mensagem_candidaturas_fechadas', models.TextField(blank=True, default='As candidaturas estão encerradas no momento.', verbose_name='Mensagem de Encerramento')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações',
                'db_table': 'configuracao',
            },
        ),
    ]
