# Generated by Django 5.2.7 on 2026-01-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_configuracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('success', 'Sucesso')], default='info', max_length=20, verbose_name='Tipo')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link de Ação')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacao',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
