# Generated by Django 5.2.7 on 2026-01-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numero_bi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número do BI'),
        ),
    ]
