# Generated by Django 5.2.7 on 2026-01-27 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_alter_aluno_numero_bi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('senha_hash', models.CharField(max_length=255, verbose_name='Senha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuário')),
                ('permissoes', models.JSONField(blank=True, default=list, verbose_name='Permissões')),
                ('papel', models.CharField(default='Comum', max_length=50, verbose_name='Papel/Role')),
                ('is_funcionario', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_perfil', to='apis.usuario', verbose_name='Usuário de Sistema'),
        ),
    ]
