# Generated by Django 5.2.7 on 2026-01-27 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_usuario_funcionario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.cargo', verbose_name='Cargo/Função'),
        ),
    ]
