# Generated by Django 5.2.7 on 2026-01-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0026_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='image/usuarios/images/', verbose_name='Foto'),
        ),
    ]
