# Generated by Django 5.2.7 on 2026-01-27 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0027_usuario_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='id_usuario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='historicologin',
            name='id_usuario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.usuario', verbose_name='Usuário'),
        ),
    ]
