# Generated by Django 5.2.7 on 2026-01-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0028_historico_id_usuario_historicologin_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
    ]
