# Generated by Django 5.2.7 on 2026-01-28 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0029_usuario_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='id_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='areaformacao',
            name='id_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_coordenadas', to='apis.funcionario', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curso_primeira_opcao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatos_opcao1', to='apis.curso'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curso_segunda_opcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatos_opcao2', to='apis.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_area_formacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.areaformacao', verbose_name='Área de Formação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos_coordenados', to='apis.funcionario', verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='chefe_id_funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos_chefiados', to='apis.funcionario', verbose_name='Chefe'),
        ),
        migrations.AlterField(
            model_name='exameadmissao',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.sala'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='id_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionario_perfil', to='apis.usuario', verbose_name='Usuário de Sistema'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id_recebedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_recebidos', to='apis.funcionario', verbose_name='Recebedor'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='id_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_responsaveis', to='apis.funcionario', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='seccao',
            name='id_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.classe', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.periodo', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas_responsaveis', to='apis.funcionario', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.sala', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.cargo', verbose_name='Cargo/Função'),
        ),
    ]
