# Generated by Django 5.2.7 on 2026-01-28 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0030_alter_aluno_id_turma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='id_coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_coordenadas', to='apis.funcionario', verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='id_tipo_disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.tipodisciplina', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='faltaaluno',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='faltaaluno',
            name='id_disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='faltaaluno',
            name='id_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='id_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.funcionario', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='id_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.turma', verbose_name='Turma'),
        ),
    ]
