# Generated by Django 5.2.7 on 2026-01-28 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0031_alter_disciplina_id_coordenador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='id_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='id_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livros_gerenciados', to='apis.funcionario', verbose_name='Responsável'),
        ),
    ]
