# Generated by Django 5.2.7 on 2026-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0032_alter_livro_id_categoria_alter_livro_id_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='turno_preferencial',
            field=models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=20, null=True),
        ),
    ]
