# Generated by Django 5.2.7 on 2026-01-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0033_alter_candidato_turno_preferencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_emissao_bi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='deficiencia',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AddField(
            model_name='aluno',
            name='local_emissao_bi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nacionalidade',
            field=models.CharField(default='Angolana', max_length=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='naturalidade',
            field=models.CharField(default='Luanda', max_length=100, verbose_name='Naturalidade (Província)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Pai'),
        ),
    ]
