# Generated by Django 5.2.7 on 2026-01-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0034_aluno_data_emissao_bi_aluno_deficiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_emissao_bi',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='deficiencia',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='local_emissao_bi',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='naturalidade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome_pai',
        ),
        migrations.AddField(
            model_name='matricula',
            name='comprovativo',
            field=models.FileField(blank=True, null=True, upload_to='comprovativos/', verbose_name='Comprovativo Pagamento'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Recibo/Bordereau'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Ativo', 'Ativo'), ('Cancelado', 'Cancelado'), ('Concluido', 'Concluído')], default='Ativo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='tipo',
            field=models.CharField(choices=[('Novo', 'Novo Ingresso'), ('Confirmacao', 'Confirmação'), ('Transferencia', 'Transferência'), ('Repetente', 'Repetente')], default='Novo', max_length=20, verbose_name='Tipo de Matrícula'),
        ),
    ]
