# Generated by Django 5.2.7 on 2026-01-31 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0035_remove_aluno_data_emissao_bi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.aluno', verbose_name='Nome Completo'),
        ),
    ]
