# Generated by Django 5.2.7 on 2026-01-31 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0036_alter_matricula_id_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='id_aluno',
            field=models.ForeignKey(help_text="Para alunos novos, use o menu 'Alunos > Adicionar' para registar dados pessoais e matrícula de uma só vez.", on_delete=django.db.models.deletion.CASCADE, to='apis.aluno', verbose_name='Nome Completo'),
        ),
    ]
