# Generated by Django 5.2.7 on 2026-01-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0037_alter_matricula_id_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='doc_bi',
            field=models.FileField(blank=True, null=True, upload_to='matriculas/documentos/', verbose_name='Cópia do BI (PDF)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='doc_certificado',
            field=models.FileField(blank=True, null=True, upload_to='matriculas/documentos/', verbose_name='Certificado/Declaração (PDF)'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='comprovativo',
            field=models.FileField(blank=True, null=True, upload_to='matriculas/comprovativos/', verbose_name='Comprovativo Pagamento'),
        ),
    ]
