# Generated by Django 5.2.7 on 2026-01-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0038_matricula_doc_bi_matricula_doc_certificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='comprovativo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='numero_recibo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='observacoes',
        ),
    ]
