# Generated by Django 5.2.7 on 2026-02-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0039_remove_matricula_comprovativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='deficiencia',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Deficiência'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nacionalidade',
            field=models.CharField(default='Angolana', max_length=50, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='doc_bi',
            field=models.FileField(blank=True, help_text='Se deixado em branco, o sistema tentará buscar o documento da última matrícula do aluno.', null=True, upload_to='matriculas/documentos/', verbose_name='Cópia do BI (PDF)'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='doc_certificado',
            field=models.FileField(blank=True, help_text='Se deixado em branco, o sistema tentará buscar o documento da última matrícula do aluno.', null=True, upload_to='matriculas/documentos/', verbose_name='Certificado/Declaração (PDF)'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo',
            field=models.CharField(choices=[('Novo', 'Novo Ingresso'), ('Confirmacao', 'Confirmação'), ('Transferencia', 'Transferência'), ('Repetente', 'Repetente'), ('Reenquadramento', 'Reenquadramento')], default='Novo', max_length=20, verbose_name='Tipo de Matrícula'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('id_aluno', 'ano_lectivo')},
        ),
    ]
