# Generated by Django 5.2.7 on 2026-02-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0040_aluno_deficiencia_aluno_nacionalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='encarregado',
            name='numero_bi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do BI'),
        ),
        migrations.AddField(
            model_name='encarregado',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
    ]
