# Generated by Django 5.2.7 on 2026-02-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0041_aluno_naturalidade_encarregado_numero_bi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='naturalidade',
            field=models.CharField(default='Luanda', max_length=100, verbose_name='Naturalidade (Local de Nascimento)'),
        ),
    ]
