# Generated by Django 5.2.7 on 2026-02-04 07:13

import apis.models.academico
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0042_candidato_municipio_candidato_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logotipo'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='nome_escola',
            field=models.CharField(default='Sistema de Gestão Escolar', max_length=255, verbose_name='Nome da Escola'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.CharField(blank=True, default=apis.models.academico.current_year, null=True, verbose_name='Ano (Legacy)'),
        ),
    ]
