# Generated by Django 5.2.7 on 2026-02-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0043_configuracao_logo_configuracao_nome_escola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status_aluno',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Transferido', 'Transferido'), ('Concluido', 'Concluído')], default='Ativo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Confirmada', 'Confirmada'), ('Concluida', 'Concluída'), ('Desistente', 'Desistente'), ('Transferido', 'Transferido')], default='Ativa', max_length=20, verbose_name='Estado'),
        ),
    ]
