# Generated by Django 5.2.7 on 2026-02-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0044_alter_aluno_status_aluno_alter_matricula_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Análise', 'Em Análise'), ('Confirmado', 'Confirmado'), ('Pago', 'Pago'), ('Agendado', 'Agendado'), ('Aprovado', 'Aprovado'), ('Não Admitido', 'Não Admitido'), ('Reprovado', 'Reprovado'), ('Matriculado', 'Matriculado')], default='Pendente', max_length=20),
        ),
    ]
