# Generated by Django 5.2.7 on 2026-02-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0045_alter_candidato_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='capacidade',
            field=models.IntegerField(default=50, verbose_name='Capacidade Máxima'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_aluno',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inativo', 'Inativo'), ('Transferido', 'Transferido'), ('Concluido', 'Concluído')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
    ]
