# Generated by Django 5.2.7 on 2026-02-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0046_turma_capacidade_alter_aluno_status_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='capacidade',
            field=models.IntegerField(default=55, verbose_name='Capacidade de Alunos'),
        ),
    ]
