# Generated by Django 5.2.7 on 2026-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0047_alter_turma_capacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='data_emissao_referencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão da Referência'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='referencia_expirada',
            field=models.BooleanField(default=False, verbose_name='Referência Expirada'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='referencia_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Referência RUPE/Pagamento'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='nome_escola',
            field=models.CharField(default='Sistema Gestão de Matricula', max_length=200, verbose_name='Nome da Escola'),
        ),
    ]
