# Generated by Django 5.2.7 on 2026-02-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0048_fatura_data_emissao_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='id_aluno',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='id_responsavel',
        ),
        migrations.RemoveField(
            model_name='solicitacaodocumento',
            name='id_aluno',
        ),
        migrations.RemoveField(
            model_name='solicitacaodocumento',
            name='id_encarregado',
        ),
        migrations.RemoveField(
            model_name='solicitacaodocumento',
            name='id_funcionario',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.DeleteModel(
            name='SolicitacaoDocumento',
        ),
    ]
