# Generated by Django 5.2.7 on 2026-02-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0049_remove_unused_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='data_fim_candidatura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Término das Candidaturas'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='fechamento_automatico',
            field=models.BooleanField(default=False, verbose_name='Fechar Automaticamente no Limite'),
        ),
    ]
