# Generated by Django 5.2.7 on 2026-02-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0050_configuracao_data_fim_candidatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anolectivo',
            name='status',
            field=models.CharField(choices=[('Planeado', 'Planeado'), ('Activo', 'Activo'), ('Encerrado', 'Encerrado'), ('Suspenso', 'Suspenso')], default='Planeado', max_length=20, verbose_name='Estado'),
        ),
    ]
