# Generated by Django 5.2.7 on 2026-02-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0051_anolectivo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero_sala',
            field=models.SmallIntegerField(unique=True, verbose_name='Número da Sala'),
        ),
    ]
