# Generated by Django 5.2.7 on 2026-02-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0052_alter_curso_nome_curso_alter_sala_numero_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='anolectivo',
            name='data_exame_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Exame de Admissão'),
        ),
        migrations.AddField(
            model_name='anolectivo',
            name='data_teste_diagnostico',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Teste de Diagnóstico'),
        ),
        migrations.AddField(
            model_name='anolectivo',
            name='fim_inscricoes',
            field=models.DateField(blank=True, null=True, verbose_name='Fim das Inscrições'),
        ),
        migrations.AddField(
            model_name='anolectivo',
            name='fim_matriculas',
            field=models.DateField(blank=True, null=True, verbose_name='Fim das Matrículas'),
        ),
        migrations.AddField(
            model_name='anolectivo',
            name='inicio_inscricoes',
            field=models.DateField(blank=True, null=True, verbose_name='Início das Inscrições'),
        ),
        migrations.AddField(
            model_name='anolectivo',
            name='inicio_matriculas',
            field=models.DateField(blank=True, null=True, verbose_name='Início das Matrículas'),
        ),
    ]
