# Generated by Django 5.2.7 on 2026-02-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0053_anolectivo_data_exame_admissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anolectivo',
            name='fecho_automatico_inscricoes',
            field=models.BooleanField(default=False, verbose_name='Fechar Inscrições Automaticamente?'),
        ),
        migrations.AddField(
            model_name='anolectivo',
            name='hora_fechamento',
            field=models.TimeField(default='23:59', help_text='Hora que o sistema encerra as operações no dia limite', verbose_name='Hora de Fechamento'),
        ),
    ]
