# Generated by Django 5.2.7 on 2026-02-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0054_anolectivo_fecho_automatico_inscricoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='vagas',
            field=models.IntegerField(default=0, verbose_name='Vagas Totais'),
        ),
    ]
