# Generated by Django 5.2.7 on 2026-02-21 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0055_curso_vagas'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('vagas', models.IntegerField(default=0, verbose_name='Quantidade de Vagas')),
                ('ano_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_cursos', to='apis.anolectivo')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_por_ano', to='apis.curso')),
            ],
            options={
                'verbose_name': 'Vaga por Curso',
                'verbose_name_plural': 'Vagas por Cursos',
                'db_table': 'vaga_curso',
                'unique_together': {('id_curso', 'ano_lectivo')},
            },
        ),
    ]
