# Generated by Django 5.2.7 on 2026-02-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0056_vagacurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagacurso',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], default='Aberto', max_length=20),
        ),
    ]
