# Generated by Django 5.2.7 on 2026-02-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0057_vagacurso_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Concluida', 'Concluída'), ('Desistente', 'Desistente'), ('Transferido', 'Transferido')], default='Ativa', max_length=20, verbose_name='Estado'),
        ),
    ]
