# Generated by Django 5.2.7 on 2026-02-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0058_alter_matricula_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='vagas',
        ),
    ]
