# Generated by Django 5.2.7 on 2026-02-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0059_remove_curso_vagas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagacurso',
            name='status',
        ),
    ]
