# Generated by Django 5.2.7 on 2026-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0060_remove_vagacurso_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='tipo_accao',
            field=models.CharField(editable=False, max_length=255, verbose_name='Tipo de Ação'),
        ),
    ]
