# Generated by Django 5.2.7 on 2026-02-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0061_alter_historico_tipo_accao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rupecandidato',
            options={'verbose_name': 'RUP Candidato', 'verbose_name_plural': 'RUPs Candidatos'},
        ),
        migrations.RenameField(
            model_name='rupecandidato',
            old_name='id_rupe',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='rupecandidato',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='rupecandidato',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='rupecandidato',
            name='status',
        ),
        migrations.AddField(
            model_name='rupecandidato',
            name='codigo_rup',
            field=models.CharField(default='SIMULADO', max_length=50, unique=True, verbose_name='Código RUP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rupecandidato',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração'),
        ),
        migrations.AddField(
            model_name='rupecandidato',
            name='data_geracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração'),
        ),
        migrations.AddField(
            model_name='rupecandidato',
            name='inscricao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rupes', to='apis.candidato', verbose_name='Dono do RUP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rupecandidato',
            name='referencia_banco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência Banco'),
        ),
        migrations.AddField(
            model_name='rupecandidato',
            name='resposta_api',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rupecandidato',
            name='status_rup',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('PAGO', 'PAGO'), ('EXPIRADO', 'EXPIRADO'), ('CANCELADO', 'CANCELADO')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='rupecandidato',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='rupecandidato',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='rupecandidato',
            table='rup_candidato',
        ),
    ]
