# Generated by Django 5.2.7 on 2026-02-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0062_alter_rupecandidato_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='numero_inscricao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Inscrição'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='status',
            field=models.CharField(choices=[('INSCRITO', 'INSCRITO'), ('AUSENTE', 'AUSENTE'), ('CLASSIFICADO', 'CLASSIFICADO'), ('NAO_CLASSIFICADO', 'NAO_CLASSIFICADO'), ('MATRICULADO', 'MATRICULADO')], default='INSCRITO', max_length=20),
        ),
    ]
