# Generated by Django 5.2.7 on 2026-02-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0063_matricula_numero_inscricao_alter_candidato_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='numero_inscricao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro/Cidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone'),
        ),
    ]
