# Generated by Django 5.2.7 on 2026-03-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0064_remove_matricula_numero_inscricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoBackup',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora Programada')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição/Motivo')),
                ('notificado', models.BooleanField(default=False, verbose_name='Já Notificado?')),
                ('executado', models.BooleanField(default=False, verbose_name='Executado?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agendamento de Backup',
                'verbose_name_plural': 'Agendamentos de Backup',
                'db_table': 'agendamento_backup',
                'ordering': ['data_hora'],
            },
        ),
    ]
