# Generated by Django 5.2.7 on 2026-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0065_agendamentobackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvento',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('evento', 'Evento Escolar'), ('feriado', 'Feriado Local'), ('lembrete', 'Lembrete'), ('outro', 'Outro')], default='evento', max_length=20)),
                ('cor', models.CharField(default='#3b82f6', help_text='Cor em Hexadecimal', max_length=7)),
            ],
            options={
                'verbose_name': 'Evento da Agenda',
                'verbose_name_plural': 'Eventos da Agenda',
                'db_table': 'agenda_eventos',
                'ordering': ['data', 'hora'],
            },
        ),
    ]
