# Generated by Django 5.2.7 on 2026-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0066_agendaevento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendaEvento',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='email_admin',
            field=models.EmailField(blank=True, help_text='Exibido na página de login para contacto', max_length=254, null=True, verbose_name='Email do Administrador'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='telefone_admin',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone do Administrador'),
        ),
    ]
