# Generated by Django 5.2.7 on 2026-03-13 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0067_add_admin_contact_to_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='email_admin',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='telefone_admin',
        ),
        migrations.AddField(
            model_name='candidato',
            name='candidatura_anterior',
            field=models.ForeignKey(blank=True, help_text='Vincula esta candidatura ao histórico de anos anteriores do mesmo candidato.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidaturas_seguintes', to='apis.candidato'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='numero_bi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='status',
            field=models.CharField(choices=[('INSCRITO', 'INSCRITO'), ('AUSENTE', 'AUSENTE'), ('LISTA_ESPERA', 'LISTA DE ESPERA'), ('CLASSIFICADO', 'CLASSIFICADO'), ('NAO_CLASSIFICADO', 'NAO_CLASSIFICADO'), ('MATRICULADO', 'MATRICULADO')], default='INSCRITO', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='candidato',
            unique_together={('numero_bi', 'ano_lectivo')},
        ),
    ]
