# Generated by Django 5.2.7 on 2026-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0068_remove_configuracao_email_admin_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidato',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(fields=('numero_bi', 'ano_lectivo'), name='unique_bi_por_ano_lectivo'),
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='candidatura_anterior',
        ),
    ]
