# Generated by Django 5.2.7 on 2026-04-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0069_alter_candidato_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaespera',
            options={'ordering': ['data_entrada'], 'verbose_name': 'Lista de Espera', 'verbose_name_plural': 'Listas de Espera'},
        ),
        migrations.AddField(
            model_name='historicologin',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('encerrada', 'Encerrada'), ('expirada', 'Expirada')], default='activa', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='historicologin',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atividade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_aluno',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Transferido', 'Transferido'), ('Concluido', 'Concluído')], default='Ativo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='anolectivo',
            name='status',
            field=models.CharField(choices=[('Planeado', 'Planeado'), ('Ativo', 'Ativo'), ('Encerrado', 'Encerrado'), ('Suspenso', 'Suspenso')], default='Planeado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status_funcionario',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inactivo', 'Inactivo'), ('Demitido', 'Demitido'), ('Banido', 'Banido')], default='Ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
