# Generated by Django 5.2.7 on 2026-04-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0070_alter_listaespera_options_historicologin_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='numero_matricula',
        ),
        migrations.AddField(
            model_name='matricula',
            name='numero_matricula',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Número de Matrícula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(default='Normal', max_length=50, verbose_name='Papel/Role'),
        ),
    ]
