# Generated by Django 6.0.4 on 2026-04-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0071_remove_aluno_numero_matricula_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(fields=('email', 'ano_lectivo'), name='unique_email_por_ano_lectivo'),
        ),
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(fields=('telefone', 'ano_lectivo'), name='unique_telefone_por_ano_lectivo'),
        ),
    ]
