# Generated by GPT-5.2 on 2026-04-22

from django.db import migrations, models


def copy_old_numero_to_text(apps, schema_editor):
    Matricula = apps.get_model('apis', 'Matricula')
    # Copiar valores existentes (BigInteger) para o campo texto
    for m in Matricula.objects.all().only('id_matricula', 'numero_matricula', 'numero_matricula_text'):
        if m.numero_matricula is not None and not m.numero_matricula_text:
            m.numero_matricula_text = str(m.numero_matricula)
            m.save(update_fields=['numero_matricula_text'])


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0072_candidato_unique_email_por_ano_lectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='numero_matricula_text',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Matrícula'),
        ),
        migrations.RunPython(copy_old_numero_to_text, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='matricula',
            name='numero_matricula',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='numero_matricula_text',
            new_name='numero_matricula',
        ),
    ]

