# Generated by Django 6.0.4 on 2026-04-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0073_matricula_numero_matricula_to_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('Sala de Aula', 'Sala de Aula'), ('Laboratório', 'Laboratório'), ('Auditório', 'Auditório'), ('Outro', 'Outro')], default='Sala de Aula', max_length=50, verbose_name='Tipo de Sala'),
        ),
    ]
